### ISSUE TITLE
Crashes on many actual scripts

### ISSUE THREAD

**Issue by anordal** [wpomier/checkshvar#1]
Try these commands:

    echo '#' | ./checkshellvar
    echo 'f(){}' | ./checkshellvar

**Comment by wpomier** [comment]
Added support to shell functions (your second line). I don't know what you mean with your first line, it runs fine to me. Here's the output:
```
$ echo '#' | ./checkshellvar
#
$ echo 'f(){}' | ./checkshellvar
f(){}
```
One more thing: shell inline docs are not supported. You will have to take care of them manually.

PS. This code was meant to be the answer to your [SO question](http://stackoverflow.com/questions/41104131/tool-to-automatically-rewrite-a-bash-script-with-proper-quoting/41113090), in an attempt to help giving you a **base** to work with. Please don't take me bad, but it was not buyed and it will not be supported any longer. If you think it deserves you can upvote and accept my answer.

**Comment by anordal** [comment]
Yes, now I can't crash it anymore. Thanks for warning about heredocs. FTR, it doesn't crash on heredocs, but that's not to say it's supported, I see what you mean.

Your second commit fixed my first example (crash on comments).

**Comment by wpomier** [comment]
The program works on one char at a time (peeking the next one), that's why I didn't even try to treat here-docs.

One last thing... on opening the link to answer this I saw that I've forgotten an `else` after checking the escape char. I added it now, but the damage is done: the previous version completly ignores backslash escape sequences. Sorry for that.
